### PR TITLE
Use cysignals hook

### PR DESCRIPTION
**Pull request by kliem**
@mkoeppe @videlec 

This branch inserts the hooks as discussed in #109.
What do you think?

It's based upon https://github.com/sagemath/cysignals/pull/166.

### CODE REVIEW

**Comment by kliem** [comment]
According to https://github.com/kliem/cypari2/runs/6660982099?check_suite_focus=true
this approach works at least for the test suite (usually there are quite a lot time outs, as the current github workflow does not build cysignals linked to pari).

**Comment by videlec** [comment]
Great! Thanks for working on it. It will simplify a lot the distribution of `cysignals`.

**Comment by mkoeppe** [comment]
Looking great!

**Comment by videlec** [comment]
Why did you bump the version here? Just for testing purposes? I do not see why a version bump would be inside a merge request.

**Comment by kliem** [comment]
I don't know how this usually works. I just think it's irritating when the version number does not reflect the current status.
Anyway the version bump is mostly needed for testing purposes, so that I can make https://github.com/kliem/cypari2/releases/tag/v2.2.0a0 and use it on https://trac.sagemath.org/ticket/33878, which in return uses it for the test in https://github.com/sagemath/cysignals/pull/166.

**Comment by kliem** [comment]
This pull request isn't ready yet anyway, as it depends on a cysignals version, which isn't even released yet.

**Comment by dimpase** [comment]
What's needed for this to make it? Is [sagemath/cysignals](https://github.com/sagemath/cysignals) ready for a new release?

**Comment by dimpase** [comment]
It would be nice to have a new release here soon, to let Pari 2.15 upgrade into Sage

**Comment by dimpase** [comment]
I don't see how `VERSION` is needed anywhere, apart from new releases. After all, our GH Actions checks are triggered by new pushes/PRs, not by version changes.

**Comment by kliem** [comment]
I just think merging a pull request and leaving the VERSION at an actual
released version could be confusing.

**Comment by mkoeppe** [comment]
Some projects solve this problem by making a commit that changes the version to some ".dev0" version right after a release

**Comment by dimpase** [comment]
bumping up VERSION with every merged PR isn't feasible, IMHO.

**Comment by dimpase** [comment]
OK, I've resolved this merge to be as supplied by the PR

**Pull request merged**
