### PR TITLE
Complex leak

### LINKED ISSUE #81: leak with `pari(xxx)`
As reported in [SageMath trac ticket #27605](https://trac.sagemath.org/ticket/27605#comment:21)
```
>>> import cypari2
>>> pari = cypari2.Pari()
>>> x = pari('1 + 1*I')
>>> complex(x)
(1+1j)
>>> del x
sys:1: RuntimeWarning: cypari2 leaked 48 bytes on the PARI stack
```

### PR DESCRIPTION
**Pull request by videlec**
Fixes #81

### CODE REVIEW

**Comment by videlec** [comment]
Except the copy, the implementations of `greal` and `real_i` are exactly the same (`src/basemath/gen3.c`). Though, they are not safe wrt to copies. Namely, for non basic number types (e.g. polynomials) the implementation relies on `op_ReIm` which does some copies (or raise an error).

What about raising an error a priori if the PARI type is not one of `t_INT`, `t_REAL`, `t_FRAC`, `t_COMPLEX`, `t_QUAD`?

**Comment by videlec** [comment]
And for `t_QUAD` the implementation is weird: it does return the coefficients (and not the real/complex part).
```
? w1 = quadgen(-23);
? real(w1)
%10 = 0
? imag(w1)
%11 = 1
```
But the number is
```
? 1.0*w1
%12 = 0.50000000000000000000000000000000000000 + 2.3979157616563597707987190320813469600*I
```

**Comment by culler** [comment]
I tested the change greal ->real_i; gimag ->imag_i by making that change in Sage 8.9-beta3 and running the SnapPy doctests.  There are no longer any leak warnings, whereas we were getting 6 or 7 warnings before.

Well done!

**Comment by videlec** [comment]
> And for `t_QUAD` the implementation is weird: it does return the coefficients (and not the real/complex part).
> 
> ```
> ? w1 = quadgen(-23);
> ? real(w1)
> %10 = 0
> ? imag(w1)
> %11 = 1
> ```
> 
> But the number is
> 
> ```
> ? 1.0*w1
> %12 = 0.50000000000000000000000000000000000000 + 2.3979157616563597707987190320813469600*I
> ```

According to the pari dev, this is an "old design bug"...

**Comment by videlec** [comment]
Here is a more down to earth conversion. It fixes the leak as well as the conversion from `t_QUAD`.

@jdemeyer I let you check amd merge.

**Comment by jdemeyer** [comment]
See #86 for a simpler solution.

**Pull request closed without merging**
