### PR TITLE
Prepare release 2.1.4

### PR DESCRIPTION
**Pull request by mkoeppe**

### CODE REVIEW

**Comment by mkoeppe** [comment]
@videlec @dimpase Please merge and tag

**Review by dimpase — APPROVED** [review]
OK

**Comment by dimpase** [comment]
I'll open a Sage PR to update cypari2

**Comment by mkoeppe** [comment]
twine upload first please

**Comment by dimpase** [comment]
yeah, I was about to say this. I'm not sure I have the right tokens, can you do this?

**Comment by mkoeppe** [comment]
I'm not a maintainer of https://pypi.org/project/cypari2/ either. @videlec could you give the necessary rights to @dimpase please?

**Comment by dimpase** [comment]
@videlec - please either put the new release to PyPI, or give one of us permissions to do so.

**Comment by dimpase** [comment]
ping

**Pull request merged**
