### PR TITLE
update pari url and fix polisirreducible

### PR DESCRIPTION
**Pull request by videlec**
- 2.11.2 is out
- 2.12.0 is the new alpha

### CODE REVIEW

**Comment by jdemeyer** [comment]
Can you explain the exclusions?

**Comment by videlec** [comment]
No real explanation. I was trying to avoid the many builds on travis.

Since the limit is 200 jobs, perhaps it does not really matter.

**Comment by videlec** [comment]
Does not compile with the latest alpha...

**Comment by videlec** [comment]
One of the issue is the renaming `isirreducible` -> `polisirreducible`.

**Comment by videlec** [comment]
This is actually the only issue :-) I am not sure how to deal with it while remaining compatible with previous versions. The problem is the presence of the custom [polisirreducible in gen.pyx](https://github.com/sagemath/cypari2/blob/master/cypari2/gen.pyx#L4106-L4114).

**Comment by jdemeyer** [comment]
I'll have a look.

**Comment by videlec** [comment]
I thought quickly about this. One simple way is to simply trash the custom `polisirreducible` in `gen.pyx`. It does work but make disappear `pari.polisirreducible` when cypari2 is compiled with older PARI versions.

**Pull request closed without merging**
