### PR TITLE
provide PARI_SIGINT_block/pending address for cysignals

### PR DESCRIPTION
**Pull request by kliem**
We provide the addresses of `PARI_SIGINT_block` and `PARI_SIGINT_pending` on runtime in python functions, such that `cysignals` can use it with `try ... except ImportError`.

### CODE REVIEW

**Comment by kliem** [comment]
@videlec

Any opinions about this approach? This would make it lots easier to build cysignals and cypari along with https://github.com/kliem/cysignals/tree/discover_cypari_on_runtime/src/cysignals.

The behaviour should be equivalent to the current approach.

**Comment by videlec** [comment]
Sounds reasonable. One problem I see with this approach is that loading `cysignals` will load `cypari2` (or at least `cypari2.paridecl`). Ideally, `cysignals` should have an abstract mechanism to plug in third-party libraries signal handling. And then it would be the job of `cypari2` to plug itself in `cysignals` at load time.

**Comment by videlec** [comment]
Not sure I agree. I wanted to suggest that `cysignals` could be configurable via hooks. There should be a single implementation of `sig_on`/`sig_off`/`sig_check` inside `cysignals`. But it should be possible to plug extra steps to `cysigs_interrupt_handler` via hooks (one has to design a generic enough protocol though).

**Comment by kliem** [comment]
When should the hooks be called?

**Comment by videlec** [comment]
- `cypari2` would insert its hooks in `cysignals` at load time of `cypari2`
- `cysignals` would call these hooks in its `cysigs_interrupt_handler`. More precisely, `cysignals` should have a stack of hooks and go through them any time an interruption occurs.

Maybe it is not feasible. I am trying to find a flexible enough solution so that `cysignals` becomes `cypari2` agnostic.

**Comment by mkoeppe** [comment]
> * `cypari2` would insert its hooks in `cysignals` at load time of `cypari2`
> * `cysignals` would call these hooks in its `cysigs_interrupt_handler`. More precisely, `cysignals` should have a stack of hooks and go through them any time an interruption occurs.

+1 on this approach

**Comment by mkoeppe** [comment]
@kliem Closing because it is superseded by #130 if I'm not mistaken

**Pull request closed without merging**
