### PR TITLE
Repile instead of losing unwrapped GENS at the bottom of the PARI stack.

### PR DESCRIPTION
**Pull request by culler**

### CODE REVIEW

**Comment by jdemeyer** [comment]
I don't mean to be disrespectful, but this is solving the wrong problem. The way I see it, the main change that this PR makes is removing the leak warning message. So it's not solving the leak, it's just pretending that it does.

**Comment by culler** [comment]
I understand the "leak" to consist of calling reset_avma while there are unwrapped GENs on the stack that were pushed by PARI after the last wrapped GEN was pushed.   The effect of calling reset_avma in that situation is that those unwrapped GENs would become corrupted if PARI pushed something else on the stack.

This PR was meant to change that behavior.  It does not call reset_avma in the case where there are any GENs on the stack that were pushed after the last wrapped GEN.  Instead, all of those unwrapped GENS remain on the stack, but they get shifted so as to fill the space that had been occupied by the GEN whose wrapper is being deallocated.  According to my reading of the PARI documentation, calling gerepile to accomplish such a shift is how the PARI developers expect a block of garbage to be removed from their stack when the block is surrounded by non-garbage.  In this case the garbage is a GEN which is wrapped by a Python object that is being deallocated.  It does not seem to me that it is an error for unwrapped GENS to exist at the moment when a Gen object is being deallocated.  But it does seem to me to be an error to move the avma in a way that allows those unwrapped GENS to be overwritten. Since it should no longer be possible for that error to occur, I saw no need for a warning.

It is of course possible that I have misunderstood what is meant by a "leak" or that I have misread the PARI documentation or that I have not implemented what I intended to implement or that I made some other mistake.  If so, please let me know what I am missing.  Explaining that to me would certainly not be disrepectful.  In fact, I would be very grateful to be enlightened about the situation.

**Comment by jdemeyer** [comment]
I don't have time for a long reply now, feel free to ping me again next week.

**Comment by jdemeyer** [comment]
But in short: those unwrapped GENs at the bottom of the stack really are garbage, not used by anything. So "corrupting" them is not an issue. The fact that there are such GENs is a memory leak.

**Comment by culler** [comment]
After writing my last comment it occured to me that maybe you **do** think it should never happen that there are any unwrapped GENS on the PARI stack when a Gen is being deallocated, and that their existence is evidence that PARI is not properly cleaning up after itself.  Is the idea to track down every situation where PARI fails to clean up after itself, one by one, and have cypari2 do the cleanup?

**Pull request closed without merging**
