### PR TITLE
.github/workflows/main.yml: Add portability/integration testing with Sage

### PR DESCRIPTION
**Pull request by mkoeppe**
We use the reusable workflows from Sage to test portability and integration with Sage.

### CODE REVIEW

**Comment by mkoeppe** [comment]
rebased

**Comment by dimpase** [comment]
I guess this has to wait until Sage's CI is in order.

**Comment by mkoeppe** [comment]
@videlec @dimpase Ready for merging.

**Comment by dimpase** [comment]
Don't we want `docs/Makefile` and `docs/source/` in `MANIFEST.in` ?

**Comment by mkoeppe** [comment]
Let's keep this PR focused on what is in its title please.

**Comment by dimpase** [comment]
I am asking a legitimate question - you added a Makefile to Manifest, I wonder whether there are more Makefiles etc that should be added.

**Comment by mkoeppe** [comment]
> I am asking a legitimate question - you added a Makefile to Manifest, I wonder whether there are more Makefiles etc that should be added.

In this PR, no, because Sage does not do anything with cypari2 documentation.

Otherwise, also no, because when you install using pip from an sdist, the documentation is not to be built. This is something that developers would do directly in a git tree.

**Pull request merged**
