### PR TITLE
Repile instead of losing unwrapped GENS at the bottom of the PARI stack.

### PR DESCRIPTION
**Pull request by culler**

### CODE REVIEW

**Comment by videlec** [comment]
Travis-CI is uniformly not happy on Python >= 3. The command `make check` did not terminate in 10min. It is supposed to take roughly 6secs (as it did with Python 2).

**Comment by culler** [comment]
Actually Travis-CI is not happy with python > 2.7 OR pari > 2.9.4. The tests hang.  Using python 2.7 and pari-2.11.2 on my Ubuntu 18.04 system I see the same hang.  When I run the tests in verbose mode I can see where the hang occurs, namely this doctest:

>>> from cysignals.alarm import alarm, AlarmInterrupt
>>> for i in range(1, 11):
...     try:
...         alarm(i/11.0)
...         pari.binomial(2**100, 2**22)
...     except AlarmInterrupt:
...         pass

When I remove that doctest all other tests pass in about 1.8 seconds.

It is hard to imagine how my changes could cause this hang for pari > 2.9.4 but not for pari 2.9.4.  But, who knows?

**Comment by culler** [comment]
I reverted stack.pyx to the sagemath master version and ran make; make install; make check with my current installation of pari 2.11.2 and cysignals built against that libpari.  I did not get a hang in the alarm test.  I did get this:
================================================================================
Testing cypari2.pari_instance
/usr/lib/python2.7/doctest.py:1315: RuntimeWarning: cypari2 leaked 139448296 bytes on the PARI stack
  compileflags, 1) in test.globs
/usr/lib/python2.7/doctest.py:1315: RuntimeWarning: cypari2 leaked 340668368 bytes on the PARI stack
  compileflags, 1) in test.globs
/usr/lib/python2.7/doctest.py:1315: RuntimeWarning: cypari2 leaked 452984896 bytes on the PARI stack
  compileflags, 1) in test.globs
/usr/lib/python2.7/doctest.py:1315: RuntimeWarning: cypari2 leaked 374948160 bytes on the PARI stack
  compileflags, 1) in test.globs
/usr/lib/python2.7/doctest.py:1315: RuntimeWarning: cypari2 leaked 287801360 bytes on the PARI stack
  compileflags, 1) in test.globs
/usr/lib/python2.7/doctest.py:1315: RuntimeWarning: cypari2 leaked 389682368 bytes on the PARI stack
  compileflags, 1) in test.globs
/usr/lib/python2.7/doctest.py:1315: RuntimeWarning: cypari2 leaked 430085376 bytes on the PARI stack
  compileflags, 1) in test.globs
/usr/lib/python2.7/doctest.py:1315: RuntimeWarning: cypari2 leaked 326084304 bytes on the PARI stack
  compileflags, 1) in test.globs
/usr/lib/python2.7/doctest.py:1315: RuntimeWarning: cypari2 leaked 348091824 bytes on the PARI stack
  compileflags, 1) in test.globs
/usr/lib/python2.7/doctest.py:1315: RuntimeWarning: cypari2 leaked 375002688 bytes on the PARI stack
  compileflags, 1) in test.globs
================================================================================

Those are some pretty large "leaks"!  And apparently there is some interesting interaction between cysignals and remove_from_pari_stack when using pari > 2.9.4.

**Comment by culler** [comment]
The loop in the alarm test goes through 10 iterations and there are 10 leaks being reported.  The alarm is supposed to be interrupting the computation:
`pari.binomial(2**100, 2**22)`
after n seconds, with n in range(1, 11).  So the big leaks are most likely happening when the alarm rings
and the data being leaked is most likely the partially computed binomial coefficient.  And apparently it is
important to reset the avma when a computation like that is interrupted, and not try to repile a giant stack while handling the exception.  I have no idea why pari 2.9.4 might be immune to this.

**Pull request closed without merging**
